name: Build and Publish

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-arch:
          - name: Linux-amd64
            os: linux
            arch: amd64
          - name: macOS-amd64
            os: darwin
            arch: amd64
          - name: macOS-arm64
            os: darwin
            arch: arm64
          - name: Windows-amd64
            os: windows
            arch: amd64
          - name: Windows-386
            os: windows
            arch: 386 # 32bit
          - name: Linux-arm
            os: linux
            arch: arm
          - name: Linux-arm64
            os: linux
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod' # Use the Go version specified in go.mod

      - name: Cache Go dependencies and build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set Ref Name Variable
        run: |
          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
            # Use Git commit SHA as the reference when manually triggered
            ref_name=$GITHUB_SHA
          else
            ref_name=${{ github.ref_name }}
          fi
          echo "::set-env name=REF_NAME::${ref_name}"
      - name: Build for ${{ matrix.os-arch.name }}
        run: |
          mkdir -p builds/${{ matrix.os-arch.name }}
          GOARCH=${{ matrix.os-arch.arch }} GOOS=${{ matrix.os-arch.os }} go build -ldflags="-X main.version=${{ env.REF_NAME }}" -o builds/${{ matrix.os-arch.name }}/nzb-monkey-go
          zip -j "nzb-monkey-go_${{ env.REF_NAME }}-${{ matrix.os-arch.arch }}-${{ matrix.os-arch.os }}.zip" builds/${{ matrix.os-arch.name }}/nzb-monkey-go

#      - name: Upload Release Assets for ${{ matrix.os-arch.name }}
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            nzb-monkey-go_*-*-*.zip

      - name: Upload Release Assets
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nzb-monkey-go_*.zip

      - name: Upload Zip Artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: |
            nzb-monkey-go_*.zip